# Generated by Django 4.1.8 on 2023-09-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='serial',
        ),
    ]
