# Generated by Django 4.1.8 on 2023-09-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_remove_robot_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='serial',
            field=models.CharField(default='O-O', max_length=5),
            preserve_default=False,
        ),
    ]
